// <auto-generated />

namespace Wikibus.Common
{
    /// <summary>Wikibus.org Ontology (https://wikibus.org/api#).</summary>
    public static partial class Api
    {
        /// <summary>
        /// api
        /// </summary>
        public const string Prefix="api";

        /// <summary>
        /// https://wikibus.org/api#
        /// </summary>
        public const string BaseUri="https://wikibus.org/api#";

        /// <summary>
        /// The API entry point
        /// </summary>
        public const string EntryPoint = BaseUri + "EntryPoint";

        /// <summary>
        /// The wishlist item class
        /// </summary>
        public const string WishlistItem = BaseUri + "WishlistItem";

        /// <summary>
        /// The collection of wishlist items
        /// </summary>
        public const string WishlistCollection = BaseUri + "WishlistCollection";

        /// <summary>
        /// The model to upload image files
        /// </summary>
        public const string ImageUpload = BaseUri + "ImageUpload";

        /// <summary>
        /// The model to upload files
        /// </summary>
        public const string PdfUpload = BaseUri + "PdfUpload";

        /// <summary>
        /// Link to brochure collection.
        /// </summary>
        public const string brochures = BaseUri + "brochures";

        public const string brochureUploaded = BaseUri + "brochureUploaded";

        /// <summary>
        /// Link to book collection.
        /// </summary>
        public const string books = BaseUri + "books";

        /// <summary>
        /// Link to magazine collection.
        /// </summary>
        public const string magazines = BaseUri + "magazines";

        /// <summary>
        /// Link to magazine's issues.
        /// </summary>
        public const string issues = BaseUri + "issues";

        /// <summary>
        /// Link to image collection
        /// </summary>
        public const string images = BaseUri + "images";

        public const string wishlist = BaseUri + "wishlist";

        public const string wishlistItem = BaseUri + "wishlistItem";

        public const string showAll = BaseUri + "showAll";

        public const string StorageLocation = BaseUri + "StorageLocation";

        public const string storageLocation = BaseUri + "storageLocation";

        public const string withPdfOnly = BaseUri + "withPdfOnly";

        public const string withoutImages = BaseUri + "withoutImages";

        public const string AddToWishlistAction = BaseUri + "AddToWishlistAction";

        public const string ImageOrder = BaseUri + "ImageOrder";
    }
}
